const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  "2xl": 24,
  "3xl": 32,
  "4xl": 48,
  4: 4,
  8: 8,
  12: 12,
  16: 16,
  20: 20,
  24: 24,
  32: 32,
  48: 48,
} as const;

const radius = {
  xs: 6,
  sm: 6,
  md: 10,
  lg: 14,
  xl: 18,
  full: 999,
  pill: 999,
  6: 6,
  10: 10,
  14: 14,
  18: 18,
  999: 999,
} as const;

const fontFamily = {
  sans: "System",
  mono: "monospace",
} as const;

export const Tokens = {
  colors: {
    bg: "#F6F8FB",
    bgRaised: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceHi: "#FFFFFF",
    surfaceLo: "#F1F4F8",
    appBg: "#F6F8FB",
    surfaceMuted: "#F1F4F8",
    surfaceWarning: "#FCEED6",
    surfaceDanger: "#FEE4E2",

    text: "#0F172A",
    textStrong: "#0F172A",
    textBody: "#334155",
    textMuted: "#475569",
    textDim: "#64748B",
    textInverse: "#FFFFFF",

    brand: "#0F4C75",
    brandHi: "#1E6BA8",
    brandBg: "#E6F0F8",
    primary: "#0F4C75",
    primaryPressed: "#1E6BA8",

    owned: "#0F4C75",
    ownedBg: "#E6F0F8",
    ownedBorder: "#BBD3E6",
    forwarded: "#B45309",
    forwardedBg: "#FEF3E2",
    forwardedBorder: "#F4D9A6",

    success: "#0F7B5A",
    successBg: "#E5F4ED",
    warning: "#A8590B",
    warn: "#A8590B",
    warningBg: "#FCEED6",
    warnBg: "#FCEED6",
    danger: "#B42318",
    dangerBg: "#FEE4E2",
    info: "#1F5DB8",
    infoBg: "#E4EDFB",
    neutral: "#475569",
    neutralBg: "#F1F4F8",

    border: "#E3E8EF",
    borderStrong: "#CBD5E1",

    icon: "#334155",
    iconMuted: "#64748B",
    shadow: "rgba(15, 23, 42, 0.08)",
    shadowStrong: "rgba(15, 23, 42, 0.16)",
  },
  radius,
  spacing,
  fonts: fontFamily,
  type: {
    display: {
      fontSize: 28,
      lineHeight: 32,
      fontWeight: "700" as const,
      letterSpacing: -0.5,
    },
    screenTitle: {
      fontSize: 24,
      lineHeight: 30,
      fontWeight: "700" as const,
      letterSpacing: -0.4,
    },
    sectionTitle: {
      fontSize: 18,
      lineHeight: 23,
      fontWeight: "700" as const,
      letterSpacing: -0.2,
    },
    title: {
      fontSize: 16,
      lineHeight: 21,
      fontWeight: "600" as const,
      letterSpacing: -0.1,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "400" as const,
    },
    bodyStrong: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "600" as const,
    },
    label: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "500" as const,
      letterSpacing: 0,
    },
    small: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "400" as const,
    },
    micro: {
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "600" as const,
      letterSpacing: 0.35,
      textTransform: "uppercase" as const,
    },
    code: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600" as const,
      fontFamily: fontFamily.mono,
    },
  },
  shadows: {
    sm: {
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 24,
      elevation: 3,
    },
  },
  layout: {
    pagePadding: 16,
    headerHeight: 64,
    screenGap: 16,
    bottomBarInset: 16,
  },
} as const;

export const tokens = Tokens;
