name: drts-fleet-platform-prod

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: drts/api:local
    environment:
      - NODE_ENV=production
      - API_PORT=3001
    ports:
      - "3001:3001"

  tenant-portal-web:
    build:
      context: .
      dockerfile: apps/tenant-portal-web/Dockerfile
    image: drts/tenant-portal-web:local
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api

  platform-admin-web:
    build:
      context: .
      dockerfile: apps/platform-admin-web/Dockerfile
    image: drts/platform-admin-web:local
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - api

  ops-console-web:
    build:
      context: .
      dockerfile: apps/ops-console-web/Dockerfile
    image: drts/ops-console-web:local
    environment:
      - NODE_ENV=production
      - PORT=3003
    ports:
      - "3003:3003"
    depends_on:
      - api
