import { describe, expect, it, vi } from "vitest";

import { DispatchDailyRecordBuilderService } from "../../src/modules/reporting/dispatch-daily-record-builder.service";

describe("INT-REP-001 daily dispatch record joins dispatch/task data", () => {
  it("rebuilds one order row from event history and keeps arrival null without an arrived event", async () => {
    const reportingRepository = {
      loadDispatchDailyRecordSourceState: vi.fn().mockResolvedValue({
        orders: [
          {
            orderId: "order-001",
            orderNo: "ORD-001",
            orderSource: "ops_console",
            orderDomain: "owned",
            tenantId: "tenant-001",
            partnerId: "partner-001",
            partnerProgramId: null,
            partnerEntrySlug: null,
            eligibilityVerificationId: null,
            issuerAuthorizationRef: null,
            serviceBucket: "business_dispatch",
            dispatchSemantics: "reservation",
            businessDispatchSubtype: "enterprise_dispatch",
            status: "completed",
            pickup: { address: "Pickup A", lat: 25.03, lng: 121.56 },
            dropoff: { address: "Dropoff B", lat: 25.05, lng: 121.58 },
            passenger: { name: "Rider", phone: "0912345678" },
            bookingId: "booking-001",
            bookingType: "oneway",
            etaSnapshot: null,
            callId: null,
            recordingId: null,
            reservationWindowStart: "2026-06-19T08:00:00.000Z",
            reservationWindowEnd: "2026-06-19T08:30:00.000Z",
            recurrenceRule: null,
            modifiableUntil: null,
            cancelableUntil: null,
            bookedBy: null,
            onsiteContact: null,
            costCenter: null,
            vehiclePreference: null,
            benefitReference: null,
            direction: null,
            flightNo: null,
            terminal: null,
            luggageCount: null,
            notes: null,
            fixedPrice: false,
            quotedFare: null,
            quotedFareSource: null,
            quotedFareRuleVersion: null,
            manualFareOverride: null,
            exceptionHold: null,
            proofRequirements: {
              minPhotoCount: 0,
              signoffRequired: false,
              expenseProofRequired: false,
            },
            approvalState: "not_required",
            approvalRequestIds: [],
            complianceFlags: [],
            cancelledAt: null,
            cancelReason: null,
            reservationHoldStatus: "released",
            reservationHoldId: "hold-001",
            reservationHoldExpiresAt: "2026-06-19T08:17:00.000Z",
            dispatchAttemptCount: 2,
            lastDispatchFailureReason: null,
            noSupplyEscalation: null,
            dispatchTimeout: null,
            createdAt: "2026-06-19T07:55:00.000Z",
            updatedAt: "2026-06-19T09:11:00.000Z",
          },
        ],
        dispatchJobs: [
          {
            dispatchJobId: "job-001",
            orderId: "order-001",
            status: "assigned",
            mode: "auto",
            latestEtaMinutes: 9,
            createdAt: "2026-06-19T08:05:00.000Z",
            updatedAt: "2026-06-19T08:17:00.000Z",
          },
        ],
        dispatchAssignments: [
          {
            assignmentId: "assign-001",
            dispatchJobId: "job-001",
            orderId: "order-001",
            taskId: "task-001",
            vehicleId: "veh-001",
            driverId: "drv-001",
            assignmentType: "metered",
            status: "cancelled",
            acceptedAt: "2026-06-19T08:10:00.000Z",
            rejectedAt: null,
            rejectReasonCode: null,
            createdAt: "2026-06-19T08:10:00.000Z",
            updatedAt: "2026-06-19T08:15:00.000Z",
          },
          {
            assignmentId: "assign-002",
            dispatchJobId: "job-001",
            orderId: "order-001",
            taskId: "task-002",
            vehicleId: "veh-002",
            driverId: "drv-002",
            assignmentType: "metered",
            status: "completed",
            acceptedAt: "2026-06-19T08:17:00.000Z",
            rejectedAt: null,
            rejectReasonCode: null,
            createdAt: "2026-06-19T08:17:00.000Z",
            updatedAt: "2026-06-19T09:10:00.000Z",
          },
        ],
        driverTasks: [
          {
            taskId: "task-001",
            orderId: "order-001",
            dispatchJobId: "job-001",
            assignmentId: "assign-001",
            driverId: "drv-001",
            vehicleId: "veh-001",
            sourcePlatform: null,
            routeProvided: true,
            waypoints: [],
            status: "cancelled",
            acceptedAt: "2026-06-19T08:10:00.000Z",
            departedAt: null,
            arrivedPickupAt: null,
            startedAt: null,
            completedAt: "2026-06-19T08:15:00.000Z",
            actualDistanceKm: null,
            actualDurationSec: null,
            fare: null,
            proof: null,
          },
          {
            taskId: "task-002",
            orderId: "order-001",
            dispatchJobId: "job-001",
            assignmentId: "assign-002",
            driverId: "drv-002",
            vehicleId: "veh-002",
            sourcePlatform: null,
            routeProvided: true,
            waypoints: [],
            status: "completed",
            acceptedAt: "2026-06-19T08:17:00.000Z",
            departedAt: "2026-06-19T08:20:00.000Z",
            arrivedPickupAt: "2026-06-19T08:31:00.000Z",
            startedAt: "2026-06-19T08:40:00.000Z",
            completedAt: "2026-06-19T09:10:00.000Z",
            actualDistanceKm: 12.5,
            actualDurationSec: 1800,
            fare: null,
            proof: null,
          },
        ],
        dispatchTraceLogs: [
          {
            traceId: "trace-001",
            orderId: "order-001",
            eventType: "dispatch.matching",
            message: "dispatch.matching",
            createdAt: "2026-06-19T08:06:00.000Z",
            details: { dispatchJobId: "job-001" },
          },
          {
            traceId: "trace-002",
            orderId: "order-001",
            eventType: "dispatch.assigned",
            message: "dispatch.assigned",
            createdAt: "2026-06-19T08:10:00.000Z",
            details: { assignmentId: "assign-001", taskId: "task-001" },
          },
          {
            traceId: "trace-003",
            orderId: "order-001",
            eventType: "dispatch.reassigned",
            message: "dispatch.reassigned",
            createdAt: "2026-06-19T08:15:00.000Z",
            details: { previousAssignmentId: "assign-001", nextTaskId: "task-002" },
          },
          {
            traceId: "trace-004",
            orderId: "order-001",
            eventType: "dispatch.assigned",
            message: "dispatch.assigned",
            createdAt: "2026-06-19T08:17:00.000Z",
            details: { assignmentId: "assign-002", taskId: "task-002" },
          },
          {
            traceId: "trace-005",
            orderId: "order-001",
            eventType: "driver.started_trip",
            message: "driver.started_trip",
            createdAt: "2026-06-19T08:40:00.000Z",
            details: { taskId: "task-002" },
          },
          {
            traceId: "trace-006",
            orderId: "order-001",
            eventType: "driver.completed_trip",
            message: "driver.completed_trip",
            createdAt: "2026-06-19T09:10:00.000Z",
            details: { taskId: "task-002" },
          },
        ],
        complaintCases: [
          {
            caseNo: "CASE-001",
            caseSource: "ops",
            relatedOrderId: "order-001",
            relatedCallId: null,
            relatedIncidentId: null,
            category: "service_quality",
            severity: "normal",
            description: "Late arrival",
            assigneeId: null,
            status: "open",
            slaDueAt: "2026-06-20T00:00:00.000Z",
            slaBreach: false,
            reopenCount: 0,
            resolutionCode: null,
            closingNote: null,
            createdAt: "2026-06-19T10:00:00.000Z",
            updatedAt: "2026-06-19T10:00:00.000Z",
          },
          {
            caseNo: "CASE-002",
            caseSource: "app",
            relatedOrderId: "order-001",
            relatedCallId: null,
            relatedIncidentId: null,
            category: "service_quality",
            severity: "high",
            description: "Routing complaint",
            assigneeId: null,
            status: "open",
            slaDueAt: "2026-06-20T00:00:00.000Z",
            slaBreach: false,
            reopenCount: 0,
            resolutionCode: null,
            closingNote: null,
            createdAt: "2026-06-19T10:30:00.000Z",
            updatedAt: "2026-06-19T10:30:00.000Z",
          },
        ],
        vehicles: [
          {
            vehicleId: "veh-001",
            plateNo: "ABC-1001",
            operatingArea: "taipei",
            supportedServiceBuckets: ["business_dispatch"],
            dispatchableFlag: true,
            exclusivityApproved: true,
            insuranceStatus: "valid",
            updatedAt: "2026-06-19T08:00:00.000Z",
            supplyLifecycle: {
              contract: {
                contractId: null,
                lifecycleStatus: "active",
                startAt: null,
                endAt: null,
                updatedAt: null,
              },
              insurance: {
                policyId: null,
                lifecycleStatus: "active",
                startAt: null,
                endAt: null,
                updatedAt: null,
              },
              exclusivity: {
                lifecycleStatus: "active",
                declarationStatus: "submitted",
                declarationFileId: null,
                reviewStatus: "approved",
                providerName: null,
                effectiveStart: null,
                effectiveEnd: null,
                reviewedAt: null,
                updatedAt: null,
              },
              dispatch: {
                eligible: true,
                blockedReasons: [],
                evaluatedAt: "2026-06-19T08:00:00.000Z",
              },
              offboarding: {
                status: "none",
                reason: null,
                requestedAt: null,
                effectiveAt: null,
                completedAt: null,
                requestedBy: null,
                debrandingRequired: false,
                debrandingStatus: "not_required",
                debrandingDueAt: null,
                debrandingCompletedAt: null,
                debrandingTicketId: null,
                notes: null,
              },
              lastTrace: null,
            },
          },
          {
            vehicleId: "veh-002",
            plateNo: "ABC-2002",
            operatingArea: "taipei",
            supportedServiceBuckets: ["business_dispatch"],
            dispatchableFlag: true,
            exclusivityApproved: true,
            insuranceStatus: "valid",
            updatedAt: "2026-06-19T08:00:00.000Z",
            supplyLifecycle: {
              contract: {
                contractId: null,
                lifecycleStatus: "active",
                startAt: null,
                endAt: null,
                updatedAt: null,
              },
              insurance: {
                policyId: null,
                lifecycleStatus: "active",
                startAt: null,
                endAt: null,
                updatedAt: null,
              },
              exclusivity: {
                lifecycleStatus: "active",
                declarationStatus: "submitted",
                declarationFileId: null,
                reviewStatus: "approved",
                providerName: null,
                effectiveStart: null,
                effectiveEnd: null,
                reviewedAt: null,
                updatedAt: null,
              },
              dispatch: {
                eligible: true,
                blockedReasons: [],
                evaluatedAt: "2026-06-19T08:00:00.000Z",
              },
              offboarding: {
                status: "none",
                reason: null,
                requestedAt: null,
                effectiveAt: null,
                completedAt: null,
                requestedBy: null,
                debrandingRequired: false,
                debrandingStatus: "not_required",
                debrandingDueAt: null,
                debrandingCompletedAt: null,
                debrandingTicketId: null,
                notes: null,
              },
              lastTrace: null,
            },
          },
        ],
      }),
      upsertDispatchDailyRecords: vi.fn().mockResolvedValue(undefined),
      reportPersistenceFailure: vi.fn(),
    };

    const service = new DispatchDailyRecordBuilderService(
      reportingRepository as never,
    );

    const records = await service.rebuildForServiceDate("2026-06-19");

    expect(records).toHaveLength(1);
    expect(records[0]).toMatchObject({
      serviceDate: "2026-06-19",
      orderId: "order-001",
      firstDispatchAt: "2026-06-19T08:05:00.000Z",
      firstAssignedAt: "2026-06-19T08:10:00.000Z",
      finalDriverId: "drv-002",
      finalVehicleId: "veh-002",
      finalPlateNo: "ABC-2002",
      etaSecondsAtAssignment: 540,
      arrivedPickupAt: null,
      tripStartedAt: "2026-06-19T08:40:00.000Z",
      tripCompletedAt: "2026-06-19T09:10:00.000Z",
      redispatchCount: 1,
      complaintCount: 2,
      qualityFlags: ["ARRIVAL_EVENT_MISSING"],
    });
    expect(reportingRepository.upsertDispatchDailyRecords).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          orderId: "order-001",
          arrivedPickupAt: null,
          qualityFlags: ["ARRIVAL_EVENT_MISSING"],
        }),
      ]),
    );
  });
});
