import { describe, expect, it, vi } from "vitest";

import type {
  AdapterHealthRecord,
  CallSessionRecord,
  DispatchJobRecord,
  DriverLocationSnapshot,
  DriverRegistryRecord,
  OwnedOrderRecord,
  PartnerEligibilityReviewQueueItem,
  ReportJobRecord,
} from "@drts/contracts";

import { OperationalObservabilityService } from "../../src/modules/operational-observability/operational-observability.service";

function createDriver(
  overrides: Partial<DriverRegistryRecord>,
): DriverRegistryRecord {
  return {
    driverId: "drv-default",
    name: "Driver Default",
    supportedServiceBuckets: ["standard_taxi"],
    workState: "available",
    licensesValid: true,
    lifecycleStatus: "active",
    eligibilityBlockedReasons: [],
    dispatchEligible: true,
    createdAt: "2026-04-30T09:00:00.000Z",
    updatedAt: "2026-04-30T09:00:00.000Z",
    activatedAt: "2026-04-30T09:00:00.000Z",
    suspendedAt: null,
    retiredAt: null,
    profileUpdatedAt: null,
    deviceBindings: [],
    ...overrides,
  };
}

function createServiceFixture() {
  const orders: OwnedOrderRecord[] = [
    {
      orderId: "ord-ready-001",
      orderNo: "O-001",
      orderSource: "portal",
      orderDomain: "owned",
      tenantId: null,
      partnerId: null,
      partnerProgramId: null,
      partnerEntrySlug: null,
      eligibilityVerificationId: null,
      issuerAuthorizationRef: null,
      serviceBucket: "standard_taxi",
      dispatchSemantics: "realtime",
      businessDispatchSubtype: null,
      status: "ready_for_dispatch",
      pickup: { address: "A", lat: null, lng: null },
      dropoff: { address: "B", lat: null, lng: null },
      passenger: { name: "Rider 1", phone: "0911000001" },
      bookingId: null,
      bookingType: null,
      etaSnapshot: null,
      callId: null,
      recordingId: null,
      reservationWindowStart: null,
      reservationWindowEnd: null,
      recurrenceRule: null,
      modifiableUntil: null,
      cancelableUntil: null,
      bookedBy: null,
      onsiteContact: null,
      costCenter: null,
      vehiclePreference: null,
      benefitReference: null,
      direction: null,
      flightNo: null,
      terminal: null,
      luggageCount: null,
      notes: null,
      fixedPrice: false,
      quotedFare: null,
      quotedFareSource: null,
      quotedFareRuleVersion: null,
      manualFareOverride: null,
      exceptionHold: null,
      proofRequirements: {
        minPhotoCount: 0,
        signoffRequired: false,
        expenseProofRequired: false,
      },
      complianceFlags: [],
      cancelledAt: null,
      cancelReason: null,
      reservationHoldStatus: "not_required",
      reservationHoldId: null,
      reservationHoldExpiresAt: null,
      createdAt: "2026-04-30T10:05:00.000Z",
      updatedAt: "2026-04-30T10:05:00.000Z",
    },
    {
      orderId: "ord-recording-001",
      orderNo: "O-002",
      orderSource: "phone",
      orderDomain: "owned",
      tenantId: null,
      partnerId: null,
      partnerProgramId: null,
      partnerEntrySlug: null,
      eligibilityVerificationId: null,
      issuerAuthorizationRef: null,
      serviceBucket: "standard_taxi",
      dispatchSemantics: "realtime",
      businessDispatchSubtype: null,
      status: "recording_pending",
      pickup: { address: "C", lat: null, lng: null },
      dropoff: { address: "D", lat: null, lng: null },
      passenger: { name: "Rider 2", phone: "0911000002" },
      bookingId: null,
      bookingType: null,
      etaSnapshot: null,
      callId: "call-001",
      recordingId: null,
      reservationWindowStart: null,
      reservationWindowEnd: null,
      recurrenceRule: null,
      modifiableUntil: null,
      cancelableUntil: null,
      bookedBy: null,
      onsiteContact: null,
      costCenter: null,
      vehiclePreference: null,
      benefitReference: null,
      direction: null,
      flightNo: null,
      terminal: null,
      luggageCount: null,
      notes: null,
      fixedPrice: false,
      quotedFare: null,
      quotedFareSource: null,
      quotedFareRuleVersion: null,
      manualFareOverride: null,
      exceptionHold: null,
      proofRequirements: {
        minPhotoCount: 0,
        signoffRequired: false,
        expenseProofRequired: false,
      },
      complianceFlags: [],
      cancelledAt: null,
      cancelReason: null,
      reservationHoldStatus: "not_required",
      reservationHoldId: null,
      reservationHoldExpiresAt: null,
      createdAt: "2026-04-30T10:12:00.000Z",
      updatedAt: "2026-04-30T10:12:00.000Z",
    },
    {
      orderId: "ord-redispatch-001",
      orderNo: "O-003",
      orderSource: "portal",
      orderDomain: "owned",
      tenantId: null,
      partnerId: null,
      partnerProgramId: null,
      partnerEntrySlug: null,
      eligibilityVerificationId: null,
      issuerAuthorizationRef: null,
      serviceBucket: "standard_taxi",
      dispatchSemantics: "realtime",
      businessDispatchSubtype: null,
      status: "redispatch_required",
      pickup: { address: "E", lat: null, lng: null },
      dropoff: { address: "F", lat: null, lng: null },
      passenger: { name: "Rider 3", phone: "0911000003" },
      bookingId: null,
      bookingType: null,
      etaSnapshot: null,
      callId: null,
      recordingId: null,
      reservationWindowStart: null,
      reservationWindowEnd: null,
      recurrenceRule: null,
      modifiableUntil: null,
      cancelableUntil: null,
      bookedBy: null,
      onsiteContact: null,
      costCenter: null,
      vehiclePreference: null,
      benefitReference: null,
      direction: null,
      flightNo: null,
      terminal: null,
      luggageCount: null,
      notes: null,
      fixedPrice: false,
      quotedFare: null,
      quotedFareSource: null,
      quotedFareRuleVersion: null,
      manualFareOverride: null,
      exceptionHold: null,
      proofRequirements: {
        minPhotoCount: 0,
        signoffRequired: false,
        expenseProofRequired: false,
      },
      complianceFlags: [],
      cancelledAt: null,
      cancelReason: null,
      reservationHoldStatus: "not_required",
      reservationHoldId: null,
      reservationHoldExpiresAt: null,
      createdAt: "2026-04-30T10:15:00.000Z",
      updatedAt: "2026-04-30T10:15:00.000Z",
    },
    {
      orderId: "ord-failed-001",
      orderNo: "O-004",
      orderSource: "portal",
      orderDomain: "owned",
      tenantId: null,
      partnerId: null,
      partnerProgramId: null,
      partnerEntrySlug: null,
      eligibilityVerificationId: null,
      issuerAuthorizationRef: null,
      serviceBucket: "standard_taxi",
      dispatchSemantics: "realtime",
      businessDispatchSubtype: null,
      status: "dispatch_failed",
      pickup: { address: "G", lat: null, lng: null },
      dropoff: { address: "H", lat: null, lng: null },
      passenger: { name: "Rider 4", phone: "0911000004" },
      bookingId: null,
      bookingType: null,
      etaSnapshot: null,
      callId: null,
      recordingId: null,
      reservationWindowStart: null,
      reservationWindowEnd: null,
      recurrenceRule: null,
      modifiableUntil: null,
      cancelableUntil: null,
      bookedBy: null,
      onsiteContact: null,
      costCenter: null,
      vehiclePreference: null,
      benefitReference: null,
      direction: null,
      flightNo: null,
      terminal: null,
      luggageCount: null,
      notes: null,
      fixedPrice: false,
      quotedFare: null,
      quotedFareSource: null,
      quotedFareRuleVersion: null,
      manualFareOverride: null,
      exceptionHold: null,
      proofRequirements: {
        minPhotoCount: 0,
        signoffRequired: false,
        expenseProofRequired: false,
      },
      complianceFlags: [],
      cancelledAt: null,
      cancelReason: null,
      reservationHoldStatus: "not_required",
      reservationHoldId: null,
      reservationHoldExpiresAt: null,
      createdAt: "2026-04-30T10:00:00.000Z",
      updatedAt: "2026-04-30T10:00:00.000Z",
    },
    {
      orderId: "ord-phone-linked-001",
      orderNo: "O-005",
      orderSource: "phone",
      orderDomain: "owned",
      tenantId: null,
      partnerId: null,
      partnerProgramId: null,
      partnerEntrySlug: null,
      eligibilityVerificationId: null,
      issuerAuthorizationRef: null,
      serviceBucket: "standard_taxi",
      dispatchSemantics: "reservation",
      businessDispatchSubtype: null,
      status: "completed",
      pickup: { address: "I", lat: null, lng: null },
      dropoff: { address: "J", lat: null, lng: null },
      passenger: { name: "Rider 5", phone: "0911000005" },
      bookingId: null,
      bookingType: null,
      etaSnapshot: null,
      callId: "call-002",
      recordingId: "rec-002",
      reservationWindowStart: null,
      reservationWindowEnd: null,
      recurrenceRule: null,
      modifiableUntil: null,
      cancelableUntil: null,
      bookedBy: null,
      onsiteContact: null,
      costCenter: null,
      vehiclePreference: null,
      benefitReference: null,
      direction: null,
      flightNo: null,
      terminal: null,
      luggageCount: null,
      notes: null,
      fixedPrice: false,
      quotedFare: null,
      quotedFareSource: null,
      quotedFareRuleVersion: null,
      manualFareOverride: null,
      exceptionHold: null,
      proofRequirements: {
        minPhotoCount: 0,
        signoffRequired: false,
        expenseProofRequired: false,
      },
      complianceFlags: [],
      cancelledAt: null,
      cancelReason: null,
      reservationHoldStatus: "not_required",
      reservationHoldId: null,
      reservationHoldExpiresAt: null,
      createdAt: "2026-04-30T09:40:00.000Z",
      updatedAt: "2026-04-30T10:20:00.000Z",
    },
  ];

  const dispatchJobs: DispatchJobRecord[] = [
    {
      dispatchJobId: "job-001",
      orderId: "ord-ready-001",
      status: "queued",
      mode: "auto",
      latestEtaMinutes: 7,
      createdAt: "2026-04-30T10:05:00.000Z",
      updatedAt: "2026-04-30T10:20:00.000Z",
    },
  ];

  const callSessions: CallSessionRecord[] = [
    {
      callId: "call-001",
      callType: "booking",
      callerPhone: "0911000002",
      agentId: "agent-1",
      agentIdentityAnnounced: true,
      agentIdentityAnnouncedAt: "2026-04-30T10:12:00.000Z",
      status: "closed",
      startedAt: "2026-04-30T10:10:00.000Z",
      endedAt: "2026-04-30T10:11:00.000Z",
      recordingId: null,
      providerRecordingRef: null,
      recordingUrl: null,
      linkedOrderId: "ord-recording-001",
      linkedCaseNo: null,
      lastEtaQuotedMinutes: null,
      lastEtaQuotedAt: null,
      callbackTask: null,
      flags: [],
    },
    {
      callId: "call-002",
      callType: "booking",
      callerPhone: "0911000005",
      agentId: "agent-2",
      agentIdentityAnnounced: true,
      agentIdentityAnnouncedAt: "2026-04-30T09:40:00.000Z",
      status: "closed",
      startedAt: "2026-04-30T09:40:00.000Z",
      endedAt: "2026-04-30T09:41:00.000Z",
      recordingId: "rec-002",
      providerRecordingRef: null,
      recordingUrl: null,
      linkedOrderId: "ord-phone-linked-001",
      linkedCaseNo: null,
      lastEtaQuotedMinutes: null,
      lastEtaQuotedAt: null,
      callbackTask: null,
      flags: [],
    },
  ];

  const drivers: DriverRegistryRecord[] = [
    createDriver({ driverId: "drv-001", name: "Driver 1" }),
    createDriver({ driverId: "drv-002", name: "Driver 2" }),
    createDriver({
      driverId: "drv-003",
      name: "Driver 3",
      workState: "offline",
      dispatchEligible: false,
      eligibilityBlockedReasons: ["work_state_offline"],
    }),
  ];

  const latestDriverLocations: DriverLocationSnapshot[] = [
    {
      driverId: "drv-001",
      lat: 25.04,
      lng: 121.56,
      accuracyM: 8,
      recordedAt: "2026-04-30T10:08:00.000Z",
      updatedAt: "2026-04-30T10:08:00.000Z",
    },
  ];

  const adapterHealth: AdapterHealthRecord[] = [
    {
      platformCode: "grab_taiwan",
      status: "healthy",
      reason: "stub",
      capabilitySummary: {
        mode: "stub",
        productionStatus: "stub",
        supportsInboundWebhook: true,
        supportsOutboundActions: true,
        supportedWebhookEvents: [],
        notes: [],
      },
      credentialStatus: "stub",
      authStatus: "stub",
      webhookStatus: "stub",
      rateLimitStatus: "stub",
      lastCheckedAt: "2026-04-30T10:25:00.000Z",
      lastError: null,
      lastWebhookReceivedAt: "2026-04-30T10:24:00.000Z",
      lastRateLimitAt: null,
      lastAuthFailureAt: null,
    },
    {
      platformCode: "uber",
      status: "degraded",
      reason: "platform",
      capabilitySummary: {
        mode: "api",
        productionStatus: "production_ready",
        supportsInboundWebhook: false,
        supportsOutboundActions: true,
        supportedWebhookEvents: [],
        notes: [],
      },
      credentialStatus: "valid",
      authStatus: "authenticated",
      webhookStatus: "not_applicable",
      rateLimitStatus: "ok",
      lastCheckedAt: "2026-04-30T10:25:00.000Z",
      lastError: "Latency elevated",
      lastWebhookReceivedAt: null,
      lastRateLimitAt: null,
      lastAuthFailureAt: null,
    },
    {
      platformCode: "line-taxi",
      status: "down",
      reason: "webhook",
      capabilitySummary: {
        mode: "webhook",
        productionStatus: "production_ready",
        supportsInboundWebhook: true,
        supportsOutboundActions: true,
        supportedWebhookEvents: ["forwarder.order.received"],
        notes: [],
      },
      credentialStatus: "valid",
      authStatus: "authenticated",
      webhookStatus: "failing",
      rateLimitStatus: "ok",
      lastCheckedAt: "2026-04-30T10:25:00.000Z",
      lastError: "Heartbeat timed out",
      lastWebhookReceivedAt: "2026-04-30T10:22:00.000Z",
      lastRateLimitAt: null,
      lastAuthFailureAt: null,
    },
  ];

  const reportJobs: ReportJobRecord[] = [
    {
      jobId: "report-001",
      jobType: "dispatch_recording_index",
      format: "csv",
      status: "queued",
      filters: {},
      artifact: null,
      createdAt: "2026-04-30T10:00:00.000Z",
      updatedAt: "2026-04-30T10:00:00.000Z",
    },
    {
      jobId: "report-002",
      jobType: "partner_revenue_summary",
      format: "csv",
      status: "running",
      filters: {},
      artifact: null,
      createdAt: "2026-04-30T10:01:00.000Z",
      updatedAt: "2026-04-30T10:01:00.000Z",
    },
    {
      jobId: "report-003",
      jobType: "monthly_trip_report",
      format: "csv",
      status: "failed",
      filters: {},
      artifact: null,
      createdAt: "2026-04-30T09:55:00.000Z",
      updatedAt: "2026-04-30T09:57:00.000Z",
    },
  ];

  const eligibilityQueue: PartnerEligibilityReviewQueueItem[] = [
    {
      eligibilityVerificationId: "elig-001",
      partnerEntrySlug: "bank-alpha",
      verificationStatus: "manual_review",
      decisionSource: "manual_fallback",
      verificationReasonCode: "ISSUER_TIMEOUT",
      attemptCount: 0,
      latestAttemptStatus: null,
      latestAttemptReasonCode: null,
      manualFallback: {
        required: true,
        reasonCode: "ISSUER_TIMEOUT",
        requestedAt: "2026-04-30T10:00:00.000Z",
        requestedBy: "system:auto_fallback",
        notes: null,
      },
      requestHints: {
        cardLast4: "1234",
        flightNo: null,
      },
      verifiedAt: "2026-04-30T10:00:00.000Z",
      createdAt: "2026-04-30T10:00:00.000Z",
      updatedAt: "2026-04-30T10:00:00.000Z",
    },
    {
      eligibilityVerificationId: "elig-002",
      partnerEntrySlug: "bank-beta",
      verificationStatus: "ineligible",
      decisionSource: "issuer_realtime",
      verificationReasonCode: "CARD_NOT_ELIGIBLE",
      attemptCount: 0,
      latestAttemptStatus: null,
      latestAttemptReasonCode: null,
      manualFallback: {
        required: false,
        reasonCode: null,
        requestedAt: null,
        requestedBy: null,
        notes: null,
      },
      requestHints: {
        cardLast4: "5678",
        flightNo: null,
      },
      verifiedAt: "2026-04-30T06:00:00.000Z",
      createdAt: "2026-04-30T06:00:00.000Z",
      updatedAt: "2026-04-30T06:00:00.000Z",
    },
  ];

  const ownedMobilityService = {
    listOrders: vi.fn(() => orders),
    listDispatchJobs: vi.fn(() => dispatchJobs),
  };
  const callcenterService = {
    listCallSessions: vi.fn(() => callSessions),
  };
  const regulatoryRegistryService = {
    listDrivers: vi.fn(() => drivers),
    listLatestDriverLocations: vi.fn(() => latestDriverLocations),
  };
  const forwarderService = {
    listAdapterHealth: vi.fn(() => adapterHealth),
  };
  const reportingFilingService = {
    listReportJobs: vi.fn(() => reportJobs),
  };
  const tenantPartnerService = {
    listPartnerEligibilityReviewQueue: vi.fn(() => eligibilityQueue),
    summarizeWebhookDeliveryHealth: vi.fn(() => ({
      totalEndpoints: 4,
      activeEndpoints: 3,
      disabledEndpoints: 1,
      queuedDeliveries: 2,
      failedDeliveriesLastHour: 6,
      oldestQueuedDeliveryLagMinutes: 12,
    })),
  };

  const service = new OperationalObservabilityService(
    ownedMobilityService as never,
    callcenterService as never,
    regulatoryRegistryService as never,
    forwarderService as never,
    reportingFilingService as never,
    tenantPartnerService as never,
  );

  return {
    service,
    callcenterService,
    reportingFilingService,
    tenantPartnerService,
  };
}

describe("OperationalObservabilityService", () => {
  it("aggregates workflow metrics and raises role-routed alerts", () => {
    const { service, callcenterService, reportingFilingService } =
      createServiceFixture();

    const snapshot = service.getSnapshot(new Date("2026-04-30T10:30:00.000Z"));

    expect(callcenterService.listCallSessions).toHaveBeenCalled();
    expect(reportingFilingService.listReportJobs).toHaveBeenCalled();

    expect(snapshot.dispatch).toMatchObject({
      activeOrders: 3,
      queueDepth: 1,
      laggedOrders: 2,
      redispatchOrders: 1,
      dispatchFailedOrders: 1,
      oldestReadyOrderLagMinutes: 25,
    });
    expect(snapshot.recording).toMatchObject({
      phoneOrders: 2,
      linkedOrders: 1,
      pendingOrders: 1,
      pendingCallSessions: 1,
      missingRecordingLinks: 1,
      oldestPendingLagMinutes: 20,
      linkedRatioPercent: 50,
    });
    expect(snapshot.driverState).toMatchObject({
      totalDrivers: 3,
      availableDrivers: 2,
      dispatchEligibleDrivers: 2,
      offlineDrivers: 1,
      staleLocationDrivers: 1,
      missingLocationDrivers: 1,
      oldestLocationLagMinutes: 22,
    });
    expect(snapshot.webhook).toMatchObject({
      disabledEndpoints: 1,
      queuedDeliveries: 2,
      failedDeliveriesLastHour: 6,
      oldestQueuedDeliveryLagMinutes: 12,
    });
    expect(snapshot.eligibility).toMatchObject({
      totalReviewQueue: 2,
      manualReviewQueue: 1,
      manualFallbackQueue: 1,
      ineligibleQueue: 1,
      recentFailureCount24h: 2,
    });
    expect(snapshot.reporting).toMatchObject({
      queuedJobs: 2,
      failedJobs: 1,
      dispatchRecordingIndexQueuedJobs: 1,
    });
    expect(snapshot.adapters).toMatchObject({
      totalAdapters: 3,
      healthyAdapters: 1,
      degradedAdapters: 1,
      downAdapters: 1,
    });

    expect(snapshot.alerts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          key: "dispatch_lag",
          state: "critical",
          measuredValue: 25,
          routes: ["ops", "platform"],
        }),
        expect.objectContaining({
          key: "recording_backlog",
          state: "critical",
          measuredValue: 20,
          routes: ["ops"],
        }),
        expect.objectContaining({
          key: "driver_state_lag",
          state: "critical",
          measuredValue: 22,
          routes: ["ops"],
        }),
        expect.objectContaining({
          key: "webhook_failure_burst",
          state: "critical",
          measuredValue: 6,
          routes: ["platform"],
        }),
        expect.objectContaining({
          key: "eligibility_review_backlog",
          state: "warning",
          measuredValue: 2,
          routes: ["ops", "platform"],
        }),
      ]),
    );

    expect(snapshot.roleViews).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          route: "ops",
          alertKeys: expect.arrayContaining([
            "dispatch_lag",
            "recording_backlog",
            "driver_state_lag",
          ]),
        }),
        expect.objectContaining({
          route: "platform",
          alertKeys: expect.arrayContaining([
            "dispatch_lag",
            "webhook_failure_burst",
            "eligibility_review_backlog",
          ]),
        }),
      ]),
    );
  });
});
