import { createHash } from "node:crypto";
import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
  type S3ClientConfig,
} from "@aws-sdk/client-s3";

import type { DocumentArtifactKind } from "./document-artifact-kinds";
import type {
  DocumentArtifactEntry,
  DocumentArtifactRecord,
  DocumentArtifactStore,
  PutDocumentArtifactCommand,
  PutIfAbsentDocumentArtifactResult,
  PutIfUnchangedDocumentArtifactResult,
} from "./document-artifact.types";
import { validatePutDocumentArtifactCommand } from "./document-artifact-validation";

export const MAX_DOCUMENT_ARTIFACT_BYTES = 25 * 1024 * 1024;

const isMissing = (error: unknown) =>
  (error as { name?: string })?.name === "NoSuchKey" ||
  (error as { $metadata?: { httpStatusCode?: number } })?.$metadata
    ?.httpStatusCode === 404;

const isConditionFailed = (error: unknown) =>
  (error as { name?: string })?.name === "PreconditionFailed" ||
  (error as { $metadata?: { httpStatusCode?: number } })?.$metadata
    ?.httpStatusCode === 412;

/**
 * Shared, durable object storage for `DocumentArtifactStore`, modelled on
 * `S3RemittanceProofStorageAdapter`: a (kind, subjectId) key maps to one
 * mutable object (unlike the proof adapter's content-addressed, write-once
 * keys -- a reissued link over regenerated bytes is a legitimate overwrite
 * here, not a stale-content violation). Every Cloud Run instance that is
 * wired to the same bucket reads the exact bytes any instance last wrote,
 * including after a restart.
 *
 * `get` never trusts a stored hash as metadata: it recomputes sha256 from
 * the bytes actually read back, so corruption or an out-of-band object edit
 * surfaces as a content mismatch at the controller rather than being
 * silently served as if nothing had changed.
 */
export class S3DocumentArtifactStoreAdapter implements DocumentArtifactStore {
  private readonly client: S3Client;

  constructor(
    private readonly config: { bucket: string; clientConfig: S3ClientConfig },
    client?: S3Client,
  ) {
    this.client = client ?? new S3Client(config.clientConfig);
  }

  private key(kind: DocumentArtifactKind, subjectId: string): string {
    return `document-artifacts/${kind}/${encodeURIComponent(subjectId)}`;
  }

  /**
   * S3 always returns an `ETag` for a successful `PutObject`/`GetObject`; a
   * missing one means the response shape is not what this adapter assumes,
   * which must fail loudly rather than silently fall back to something that
   * is not actually a correct fencing token (see `putIfUnchanged`).
   */
  private requireGeneration(etag: string | undefined): string {
    if (!etag) {
      throw new Error(
        "Stored document artifact has no generation token (missing ETag).",
      );
    }
    return etag;
  }

  async put(
    command: PutDocumentArtifactCommand,
  ): Promise<DocumentArtifactRecord> {
    const { subjectId, mimeType, bytes } =
      validatePutDocumentArtifactCommand(command);
    if (bytes.length > MAX_DOCUMENT_ARTIFACT_BYTES) {
      throw new Error("DocumentArtifactStore.put exceeds the byte limit.");
    }

    const storedAt = new Date().toISOString();
    const response = await this.client.send(
      new PutObjectCommand({
        Bucket: this.config.bucket,
        Key: this.key(command.kind, subjectId),
        Body: bytes,
        ContentType: mimeType,
        ContentLength: bytes.length,
        Metadata: { "stored-at": storedAt },
      }),
    );

    return {
      kind: command.kind,
      subjectId,
      mimeType,
      sha256: createHash("sha256").update(bytes).digest("hex"),
      byteLength: bytes.length,
      storedAt,
      generation: this.requireGeneration(response.ETag),
    };
  }

  /**
   * Conditional overwrite fenced by the object's own state (`DocumentArtifactStore.putIfUnchanged`):
   * `IfNoneMatch: "*"` when the caller's baseline was "nothing stored yet",
   * `IfMatch: expectedGeneration` otherwise -- both native S3 conditional
   * `PutObject` preconditions, evaluated atomically server-side. A
   * `PreconditionFailed` response means some other write already changed
   * (or created) the object since the caller's baseline was captured; this
   * never retries or silently overwrites, it re-reads and reports whatever
   * is actually there now.
   *
   * This is what actually stops a publish attempt whose ownership claim was
   * reclaimed and finalized by another instance while this attempt's own
   * `PutObjectCommand` was still in flight (a slow network, not a slow
   * claimant) from clobbering the real winner's bytes on arrival -- a
   * database-level claim token alone fences the record, never this object.
   */
  async putIfUnchanged(
    command: PutDocumentArtifactCommand,
    expectedGeneration: string | null,
  ): Promise<PutIfUnchangedDocumentArtifactResult> {
    const { subjectId, mimeType, bytes } =
      validatePutDocumentArtifactCommand(command);
    if (bytes.length > MAX_DOCUMENT_ARTIFACT_BYTES) {
      throw new Error("DocumentArtifactStore.put exceeds the byte limit.");
    }

    const storedAt = new Date().toISOString();
    try {
      const response = await this.client.send(
        new PutObjectCommand({
          Bucket: this.config.bucket,
          Key: this.key(command.kind, subjectId),
          Body: bytes,
          ContentType: mimeType,
          ContentLength: bytes.length,
          Metadata: { "stored-at": storedAt },
          ...(expectedGeneration === null
            ? { IfNoneMatch: "*" }
            : { IfMatch: expectedGeneration }),
        }),
      );

      return {
        applied: true,
        record: {
          kind: command.kind,
          subjectId,
          mimeType,
          sha256: createHash("sha256").update(bytes).digest("hex"),
          byteLength: bytes.length,
          storedAt,
          generation: this.requireGeneration(response.ETag),
        },
      };
    } catch (error) {
      if (!isConditionFailed(error)) throw error;
      const existing = await this.get(command.kind, subjectId);
      return { applied: false, record: existing?.record ?? null };
    }
  }

  /**
   * Recovery-only conditional create: `IfNoneMatch: "*"` is S3's own atomic
   * "fail if this key already exists" guard, so this never overwrites an
   * object a concurrent recoverer (sibling instance or this same instance's
   * own retry) already wrote. A `PreconditionFailed` response means exactly
   * that race happened -- the object now exists -- so this re-reads and
   * returns the winner's record instead of trusting its own unwritten bytes.
   */
  async putIfAbsent(
    command: PutDocumentArtifactCommand,
  ): Promise<PutIfAbsentDocumentArtifactResult> {
    const { subjectId, mimeType, bytes } =
      validatePutDocumentArtifactCommand(command);
    if (bytes.length > MAX_DOCUMENT_ARTIFACT_BYTES) {
      throw new Error("DocumentArtifactStore.put exceeds the byte limit.");
    }

    const storedAt = new Date().toISOString();
    let response;
    try {
      response = await this.client.send(
        new PutObjectCommand({
          Bucket: this.config.bucket,
          Key: this.key(command.kind, subjectId),
          Body: bytes,
          ContentType: mimeType,
          ContentLength: bytes.length,
          Metadata: { "stored-at": storedAt },
          IfNoneMatch: "*",
        }),
      );
    } catch (error) {
      if (!isConditionFailed(error)) throw error;
      const existing = await this.get(command.kind, subjectId);
      if (!existing) {
        // Lost the race against a delete, not a create: the object is
        // genuinely absent again. Surface the original failure rather than
        // claiming a winner that is not actually there.
        throw error;
      }
      return { created: false, record: existing.record };
    }

    return {
      created: true,
      record: {
        kind: command.kind,
        subjectId,
        mimeType,
        sha256: createHash("sha256").update(bytes).digest("hex"),
        byteLength: bytes.length,
        storedAt,
        generation: this.requireGeneration(response.ETag),
      },
    };
  }

  async get(
    kind: DocumentArtifactKind,
    subjectId: string,
  ): Promise<DocumentArtifactEntry | null> {
    let object;
    try {
      object = await this.client.send(
        new GetObjectCommand({
          Bucket: this.config.bucket,
          Key: this.key(kind, subjectId),
        }),
      );
    } catch (error) {
      if (isMissing(error)) return null;
      throw error;
    }

    const mimeType = object.ContentType ?? "";
    if (!mimeType) {
      throw new Error("Stored document artifact has no MIME type.");
    }
    const size = object.ContentLength;
    if (
      !Number.isSafeInteger(size) ||
      !size ||
      size < 0 ||
      size > MAX_DOCUMENT_ARTIFACT_BYTES
    ) {
      throw new Error("Stored document artifact size is invalid.");
    }
    const body = object.Body as AsyncIterable<Uint8Array> | undefined;
    if (!body || typeof body[Symbol.asyncIterator] !== "function") {
      throw new Error("Unreadable document artifact body.");
    }
    const chunks: Buffer[] = [];
    let count = 0;
    for await (const part of body) {
      const chunk = Buffer.from(part);
      count += chunk.length;
      if (count > MAX_DOCUMENT_ARTIFACT_BYTES || count > size) {
        throw new Error("Stored document artifact exceeds its byte limit.");
      }
      chunks.push(chunk);
    }
    if (count !== size) {
      throw new Error("Stored document artifact length mismatch.");
    }
    const bytes = Buffer.concat(chunks);
    const storedAt =
      object.Metadata?.["stored-at"] ??
      object.LastModified?.toISOString() ??
      new Date(0).toISOString();

    return {
      record: {
        kind,
        subjectId,
        mimeType,
        sha256: createHash("sha256").update(bytes).digest("hex"),
        byteLength: bytes.length,
        storedAt,
        generation: this.requireGeneration(object.ETag),
      },
      bytes,
    };
  }
}
