// zh-TW auth copy, shared by web and future native passenger clients.
export const AUTH_COPY = {
  loginTitle: "登入或註冊",
  otpTitle: "輸入驗證碼",
  accountTitle: "我的帳號",
  phone: "手機號碼",
  email: "電子郵件",
  code: "6位數驗證碼",
  login: {
    phone: "使用手機登入",
    email: "使用 Email 登入",
    google: "使用 Google 登入",
    facebook: "使用 Facebook 登入",
    line: "使用 LINE 登入",
  },
  link: {
    phone: "綁定手機",
    email: "綁定 Email",
    google: "綁定 Google",
    facebook: "綁定 Facebook",
    line: "綁定 LINE",
  },
  resend: "重新發送",
  verifyLogin: "驗證並登入",
  verify: "確認驗證",
  back: "返回",
  retry: "重新嘗試",
  loading: "處理中...",
  loadingAccount: "載入中...",
  invalidCode: "驗證碼無效或已失效，請確認或重新取得驗證碼。",
  expired: "驗證碼已過期，請重新取得驗證碼。",
  locked: "此驗證碼已無法使用，請重新取得驗證碼。",
  rateLimit: "請求過於頻繁，請稍後再試。",
  unavailable: "服務暫時無法使用，請稍後再試。",
  unsupported: "此登入方式目前未啟用，請選擇其他方式。",
  conflict: "此登入方式已綁定其他帳號。",
  lastIdentity: "必須至少保留一種登入方式。",
  unauthorized: "登入已失效，請重新登入。",
  invalidGrant: "認證已失效，請重新開始登入或綁定。",
  denied: "已取消第三方認證。",
  invalidInput: "請確認輸入的資料。",
  pendingPayment: "尚有未結清款項，請先完成付款。",
  providersEmpty: "目前沒有可用的登入方式。",
  providersFailed: "無法載入登入方式，請重新嘗試。",
  sentTo: (target: string) => `已發送驗證碼至 ${target}`,
  cooldown: (seconds: number) => `重送驗證碼 (${seconds}s)`,
  expiry: (seconds: number) => `驗證碼有效時間剩餘 ${seconds} 秒`,
  attempts: (failures: number) =>
    `本畫面已收到 ${failures} 次無效驗證回覆（最多嘗試 5 次）；是否失效仍由伺服器判定。`,
  consentTitle: "服務條款與隱私權政策",
  consentIntro: "請先閱讀並同意服務條款與隱私權政策。",
  consentPending: "服務條款與隱私權政策尚未提供，暫時無法完成首次使用同意。",
  consentReadFailed: "無法讀取同意紀錄，請重新嘗試。",
  consentSaveFailed: "同意紀錄儲存失敗，請重新嘗試。",
  consentCheckbox: "我同意服務條款與隱私權政策",
  consentContinue: "同意並繼續",
  terms: "服務條款",
  privacy: "隱私權政策",
  consentHint: "首次使用須明確同意服務條款與隱私權政策。",
  callbackTitle: "第三方登入",
  callbackLoading: "正在驗證中，請稍候...",
  callbackMissing: "缺少認證參數。",
  backLogin: "返回登入頁",
  profile: "個人資料",
  name: "姓名",
  contactPhone: "聯絡手機",
  verified: "已驗證",
  unverified: "未驗證",
  edit: "編輯資料",
  save: "儲存變更",
  saved: "資料已更新。",
  verifyContact: "去驗證",
  saveContactFirst: "請先儲存聯絡手機後再驗證。",
  identities: "登入方式",
  unlink: "解除綁定",
  unlinkConfirm: "確定要解除這個登入方式嗎？",
  confirmUnlink: "確認解除",
  logout: "登出",
  logoutConfirm: "確定要登出嗎？",
  confirmLogout: "確認登出",
  delete: "刪除帳號",
  deleteConfirm: "確定要刪除帳號嗎？",
  confirmDelete: "確認刪除",
  cancel: "取消",
  retention:
    "刪除帳號後，個人資料將匿名化，並撤銷所有登入 session。依法律要求，行程與財務紀錄將保留。此操作無法復原。",
  accountFailed: "無法載入帳號資料，請重新嘗試。",
  operationFailed: "操作未完成，請重新嘗試。",
} as const;
