import type { AuthActorType, AuthRealm, AuthRoleFamily } from "./auth.types";

export const AUTH_METADATA_KEY = "drts:auth";
export const AUTH_OPEN_ROUTE_KEY = "drts:auth:open";
export const AUTH_REQUIRED_SCOPES_KEY = "drts:auth:scopes";
export const AUTH_ALLOWED_REALMS_KEY = "drts:auth:realms";
export const FEATURE_GATED_FLAG_KEY = "drts:feature-gate:flag-key";

export const AUTH_ANONYMOUS_REQUEST_ID = "anonymous";

export const AUTH_DEFAULT_PUBLIC_REALMS: readonly AuthRealm[] = ["system"];

export const AUTH_ROUTE_READ_METHODS = new Set(["GET", "HEAD", "OPTIONS"]);

export const AUTH_ROUTE_WRITE_METHODS = new Set([
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
]);

export const AUTH_ROLE_FAMILY_FROM_ACTOR_TYPE: Record<
  AuthActorType,
  AuthRoleFamily[]
> = {
  system: [],
  platform_admin: ["platform"],
  tenant_admin: ["tenant"],
  ops_user: ["ops"],
  driver_user: ["driver"],
  partner_api_key: ["partner"],
  referral_passenger: ["partner"],
};

const SANDBOX_COMPLIANCE_SCOPES = [
  "sandbox.compliance.read",
  "sandbox.compliance.manage",
  "sandbox.investigation.read",
  "sandbox.investigation.manage",
  "sandbox.evidence.preview",
  "sandbox.evidence.export.request",
  "sandbox.evidence.export.approve",
  "sandbox.legal_hold.place",
  "sandbox.legal_hold.release.request",
  "sandbox.legal_hold.release.approve",
  "sandbox.regulatory_report.review",
  "sandbox.regulatory_report.submit",
] as const;

const MULTI_TAXI_RATING_GOVERNANCE_SCOPES = [
  "multi_taxi_ratings:read",
  "multi_taxi_ratings:moderate",
] as const;

export const AUTH_SCOPE_PRESETS: Record<AuthActorType, readonly string[]> = {
  system: [
    "identity:read",
    "identity:sessions:read",
    "identity:sessions:write",
    "foundation:read",
    "foundation:write",
    "audit:read",
    "notifications:read",
    "notifications:write",
    "tenant:read",
    "tenant:write",
    "tenant:webhooks:read",
    "tenant:webhooks:write",
    "tenant:sla:read",
    "tenant:sla:write",
    "tenant:billing:read",
    "tenant:billing:write",
    "billing:read",
    "billing:write",
    "regulatory:read",
    "regulatory:write",
    "callcenter:read",
    "callcenter:write",
    "complaints:read",
    "complaints:write",
    "incident:read",
    "incident:write",
    "maintenance:read",
    "maintenance:write",
    "owned:read",
    "owned:write",
    "dispatch:read",
    "dispatch:write",
    "driver:read",
    "driver:write",
    "reports:read",
    "reports:write",
    "forwarder:read",
    "forwarder:write",
    ...SANDBOX_COMPLIANCE_SCOPES,
    ...MULTI_TAXI_RATING_GOVERNANCE_SCOPES,
  ],
  platform_admin: [
    "identity:read",
    "identity:sessions:read",
    "identity:sessions:write",
    "foundation:read",
    "foundation:write",
    "audit:read",
    "notifications:read",
    "notifications:write",
    "tenant:read",
    "tenant:write",
    "tenant:webhooks:read",
    "tenant:webhooks:write",
    "tenant:sla:read",
    "tenant:sla:write",
    "tenant:billing:read",
    "tenant:billing:write",
    "billing:read",
    "billing:write",
    "regulatory:read",
    "regulatory:write",
    "incident:read",
    "incident:write",
    "maintenance:read",
    "maintenance:write",
    "reports:read",
    "reports:write",
    "forwarder:read",
    ...SANDBOX_COMPLIANCE_SCOPES,
    ...MULTI_TAXI_RATING_GOVERNANCE_SCOPES,
  ],
  tenant_admin: [
    "identity:read",
    "identity:sessions:read",
    "identity:sessions:write",
    "audit:read",
    "tenant:read",
    "tenant:write",
    "tenant:webhooks:read",
    "tenant:webhooks:write",
    "tenant:sla:read",
    "tenant:sla:write",
    "tenant:billing:read",
    "tenant:billing:write",
    "billing:read",
    "billing:write",
    "reports:read",
    "reports:write",
  ],
  ops_user: [
    "identity:read",
    "identity:sessions:read",
    "identity:sessions:write",
    "audit:read",
    "notifications:read",
    "notifications:write",
    "regulatory:read",
    "regulatory:write",
    "callcenter:read",
    "callcenter:write",
    "complaints:read",
    "complaints:write",
    "incident:read",
    "incident:write",
    "maintenance:read",
    "maintenance:write",
    "owned:read",
    "owned:write",
    "dispatch:read",
    "dispatch:write",
    "driver:read",
    "billing:read",
    "billing:write",
    "reports:read",
    "reports:write",
    "forwarder:read",
    "forwarder:write",
    "sandbox.compliance.read",
    "sandbox.investigation.read",
    "sandbox.evidence.preview",
  ],
  driver_user: [
    "owned:read",
    "driver:read",
    "driver:write",
    "dispatch:read",
    "incident:write",
  ],
  partner_api_key: [
    "partner:entries:read",
    "partner:eligibility:read",
    "partner:eligibility:write",
  ],
  referral_passenger: [
    "partner:handoff",
    "partner:eligibility:read",
    "partner:eligibility:write",
    "partner:book",
  ],
};

export const AUTH_TENANT_ROLE_SCOPE_PRESETS: Record<string, readonly string[]> =
  {
    tenant_admin: [
      "identity:read",
      "identity:sessions:read",
      "identity:sessions:write",
      "audit:read",
      "tenant:read",
      "tenant:write",
      "tenant:webhooks:read",
      "tenant:webhooks:write",
      "tenant:sla:read",
      "tenant:sla:write",
      "tenant:billing:read",
      "tenant:billing:write",
      "reports:read",
      "reports:write",
    ],
    tenant_ops_admin: [
      "identity:read",
      "audit:read",
      "tenant:read",
      "tenant:write",
      "tenant:webhooks:read",
      "tenant:webhooks:write",
      "tenant:sla:read",
      "tenant:sla:write",
      "tenant:billing:read",
      "reports:read",
      "reports:write",
    ],
    tenant_finance_admin: [
      "identity:read",
      "audit:read",
      "tenant:read",
      "tenant:webhooks:read",
      "tenant:sla:read",
      "tenant:billing:read",
      "tenant:billing:write",
      "reports:read",
      "reports:write",
    ],
    tenant_viewer: [
      "identity:read",
      "audit:read",
      "tenant:read",
      "tenant:webhooks:read",
      "tenant:sla:read",
      "tenant:billing:read",
      "reports:read",
    ],
  };

export function getTenantRoleScopes(
  roleCode: string,
): readonly string[] | null {
  return AUTH_TENANT_ROLE_SCOPE_PRESETS[roleCode] ?? null;
}
