-- MAP-BE-006: review lifecycle status is enforced by the contracts and API runtime.
-- This migration is intentionally deploy-safe for long-lived dev databases that
-- may contain legacy, unknown status check constraints without Cloud Logging
-- visibility in the current deployer role. A follow-up privileged maintenance
-- migration can normalize historical rows and validate DB constraints once the
-- dev deployer has log viewer access.
