import type { ResolvedRuntimeEligibilityContext } from "../../../../apps/api/src/modules/vehicle-eligibility/eligibility-context-resolver.service";

export function createResolvedContext(
  overrides?: Partial<ResolvedRuntimeEligibilityContext>,
): ResolvedRuntimeEligibilityContext {
  return {
    orderId: "ord-001",
    dispatchJobId: "job-001",
    driverId: "drv-001",
    vehicleId: "veh-001",
    serviceProductId: "svc-001",
    serviceProductCode: "enterprise_dispatch",
    sourcePlatform: null,
    policyVersion:
      "service:svc-001@2026-06-20T00:00:00.000Z|capability:cap-001@2026-06-20T00:00:00.000Z",
    evaluatedAt: "2026-06-20T12:00:00.000Z",
    driver: {
      driverId: "drv-001",
      name: "Driver One",
      supportedServiceBuckets: ["standard_taxi", "business_dispatch"],
      workState: "available",
      licensesValid: true,
      lifecycleStatus: "active",
      eligibilityBlockedReasons: [],
      dispatchEligible: true,
      createdAt: "2026-06-20T00:00:00.000Z",
      updatedAt: "2026-06-20T00:00:00.000Z",
      activatedAt: "2026-06-20T00:00:00.000Z",
      suspendedAt: null,
      retiredAt: null,
      profileUpdatedAt: "2026-06-20T00:00:00.000Z",
      deviceBindings: [],
    },
    vehicle: {
      vehicleId: "veh-001",
      plateNo: "ABC-001",
      createdAt: "2026-06-20T00:00:00.000Z",
      operatingArea: "taichung-port",
      supportedServiceBuckets: ["business_dispatch"],
      dispatchableFlag: true,
      exclusivityApproved: true,
      insuranceStatus: "valid",
      updatedAt: "2026-06-20T00:00:00.000Z",
      supplyLifecycle: {
        contract: {
          contractId: "contract-001",
          lifecycleStatus: "active",
          startAt: "2026-06-01T00:00:00.000Z",
          endAt: null,
          updatedAt: "2026-06-20T00:00:00.000Z",
        },
        insurance: {
          policyId: "policy-001",
          lifecycleStatus: "active",
          startAt: "2026-06-01T00:00:00.000Z",
          endAt: null,
          updatedAt: "2026-06-20T00:00:00.000Z",
        },
        exclusivity: {
          lifecycleStatus: "active",
          declarationStatus: "submitted",
          declarationFileId: "decl-001",
          reviewStatus: "approved",
          providerName: "DRTS",
          effectiveStart: "2026-06-01T00:00:00.000Z",
          effectiveEnd: null,
          reviewedAt: "2026-06-20T00:00:00.000Z",
          updatedAt: "2026-06-20T00:00:00.000Z",
        },
        dispatch: {
          eligible: true,
          blockedReasons: [],
          evaluatedAt: "2026-06-20T00:00:00.000Z",
        },
        offboarding: {
          status: "none",
          reason: null,
          requestedAt: null,
          effectiveAt: null,
          completedAt: null,
          requestedBy: null,
          debrandingRequired: false,
          debrandingStatus: "not_required",
          debrandingDueAt: null,
          debrandingCompletedAt: null,
          debrandingTicketId: null,
          notes: null,
        },
        lastTrace: null,
      },
    },
    vehicleCapability: {
      capabilityId: "cap-001",
      vehicleId: "veh-001",
      licenseType: "business_vehicle",
      supportedProducts: [
        "enterprise_dispatch",
        "credit_card_airport_transfer",
      ],
      seatCount: 5,
      luggageCapacity: 4,
      airportPermit: true,
      businessDispatchEligible: true,
      taxiMeterRequired: false,
      fixedFareAllowed: true,
      conditionallyAllowed: false,
      requiredDocuments: [],
      trainingRequired: false,
      permitRequired: false,
      platformForwardingAllowed: false,
      active: true,
      effectiveFrom: "2026-06-01T00:00:00.000Z",
      effectiveUntil: null,
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: "2026-06-20T00:00:00.000Z",
    },
    serviceProduct: {
      serviceProduct: "enterprise_dispatch",
      displayName: "Enterprise Dispatch",
      timing: "reservation",
      active: true,
      serviceBucket: "business_dispatch",
      allowedLicenseTypes: [
        "taxi",
        "multi_purpose_taxi",
        "rental_car",
        "business_vehicle",
      ],
      meterRequired: false,
      fixedFareAllowed: true,
      requiresBusinessDispatchEligible: true,
      requiresAirportPermit: false,
      requiresPlatformForwardingAllowed: false,
      defaultProofRequirements: ["photo"],
    },
    currentLocation: {
      driverId: "drv-001",
      lat: 24.266,
      lng: 120.62,
      accuracyM: 30,
      recordedAt: "2026-06-20T11:59:00.000Z",
      updatedAt: "2026-06-20T11:59:00.000Z",
    },
    platformBindings: [],
    driverReadiness: {
      ready: true,
      reasonCodes: [],
    },
    vehicleReadiness: {
      ready: true,
      reasonCodes: [],
    },
    ...overrides,
  };
}
