export {
  DRIVER_LEAVE_TYPES,
  type DriverLeaveType,
  DRIVER_LEAVE_STATUSES,
  type DriverLeaveStatus,
  MAX_PAST_APPLICATION_GRACE_MS,
  type DriverLeaveRecord,
  type CreateDriverLeaveCommand,
  type WithdrawDriverLeaveCommand,
  type ReviewDriverLeaveCommand,
  type DriverLeaveQueryFilter,
} from "@drts/contracts";

export const DRIVER_LEAVE_ERROR_CODES = {
  LEAVE_INVALID_TIME_RANGE: "LEAVE_INVALID_TIME_RANGE",
  LEAVE_MISSING_REQUIRED_FIELDS: "LEAVE_MISSING_REQUIRED_FIELDS",
  LEAVE_FORBIDDEN_ACCESS: "LEAVE_FORBIDDEN_ACCESS",
  LEAVE_NOT_FOUND: "LEAVE_NOT_FOUND",
  LEAVE_OVERLAPPING_REQUEST: "LEAVE_OVERLAPPING_REQUEST",
  LEAVE_INVALID_STATE_TRANSITION: "LEAVE_INVALID_STATE_TRANSITION",
  DRIVER_ON_LEAVE: "DRIVER_ON_LEAVE",
} as const;
